name: FlutterTube
description: A lite Youtube built with Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  flutter_youtube: ^1.1.4
  http: ^0.12.0
  shared_preferences: ^0.4.3
  rxdart: ^0.20.0
  bloc_pattern: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  